FROM debian:11.0

ARG DEBIAN_FRONTEND=noninteractive

RUN set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               build-essential \
               cdbs \
               devscripts \
               equivs \
               fakeroot \
               dpkg-dev \
               uuid-dev \
               libmodsecurity3 \
               libmodsecurity-dev \
               libmaxminddb-dev \
               lsb-release \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* \
    && uname -a
