FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN set -ex \
    && sed -i -- 's/# deb-src/deb-src/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
               build-essential \
               cdbs \
               devscripts \
               equivs \
               fakeroot \
               dpkg-dev \
               uuid-dev \
               libmodsecurity3 \
               libmodsecurity-dev \
               lsb-release \
    && apt-get build-dep -y --no-install-recommends \
               nginx \
    && apt-get clean \
    && rm -rf /tmp/* /var/tmp/* \
    && uname -a
